question_data = [{"category": "Mythology", "type": "boolean", "difficulty": "easy",
                  "question": "In Norse mythology, Thor once dressed as a woman.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "The proof for the Chinese Remainder Theorem used in Number Theory was NOT developed by its first publisher, Sun Tzu.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Tony Hawk's Pro Skater was released in 1999.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "hard",
                                                    "question": "Switzerland has four national languages, English being one of them.",
                                                    "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Rhode Island is actually located on the US mainland, despite its name.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
                  "question": "In 'JoJo's Bizarre Adventure', Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "The Paradox Interactive game 'Stellaris' was released in 2016.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
